### ISSUE TITLE
導入Travis-CI

### ISSUE THREAD

**Issue by touhonoob** [scribetw/pixmicat#18]
可以自動用多個PHP版本跑測試
https://github.com/touhonoob/pixmicat/commit/84c0aba6a3a757bbaee8bdd8687229b8c6300da4#diff-d41d8cd98f00b204e9800998ecf8427e
https://travis-ci.org/touhonoob/pixmicat

**Comment by touhonoob** [comment]
最近發現一個用基於docker的CI也不錯用
https://drone.io/

**Comment by scribetw** [comment]
這個好耶，很敢給，支援的語言也多。

**Comment by touhonoob** [comment]
https://drone.io/github.com/touhonoob/pixmicat/11
**Commands**
```shell
git checkout develop
wget https://getcomposer.org/composer.phar
chmod +x composer.phar
./composer.phar install
cd TestCase
phpunit -d date.timezone=UTC
```

**Comment by scribetw** [comment]
咦，Drone.io 不是放設定檔在 repo 而是直接在 CI 上設定嗎？

**Comment by touhonoob** [comment]
他的設定好像都在網站上
不像travis要新增一個檔案

**Comment by scribetw** [comment]
@touhonoob 那我先試看看 Drone.io 好了，不然不會寫 .travis.yml 怕多餘 push 很醜 XD

**Comment by scribetw** [comment]
喔，Drone.io 的 PHP 只有 5.4，不過可能是 Beta 階段比較沒得選。

**Comment by scribetw** [comment]
暫時先以 drone.io 導入結案。日後再看看有沒有需要轉到 Travis-CI。

重點其實不是在哪個持續整合平台，而是老舊的程式邏輯不利於測試。
需要逐步重構翻新提昇可測試性。

**Comment by scribetw** [comment]
https://github.com/drone/drone/blob/v0.2.1/README.md#builds

有 `.drone.yml` 可以寫的樣子，而且還能指定 Docker Image，喔 PHP 那要什麼版本都可以自己做了。
暫時還沒研究。

**Comment by touhonoob** [comment]
據說只有自己架才能用.drone.yml
drone.io上沒辦法用
https://github.com/drone/drone/issues/680#issuecomment-62296471

**Comment by Kennyl** [comment]
其實 shippable 也是docker base 支持5.3-> 5.6php
http://docs.shippable.com/en/latest/languages/php.html

**Comment by touhonoob** [comment]
@Kennyl
Shippable有針對open source projects的免費帳號嗎？

**Comment by touhonoob** [comment]
@Kennyl 
剛剛測試了一下還不錯用
只是好像要Collaborators才看得到結果？
https://github.com/touhonoob/pixmicat/blob/shippable-test/shippable.yml
![screenshot]
(http://i.imgur.com/9EnU52W.png)

**Comment by Kennyl** [comment]
因為每push 一次，它會自動run 1 次.或者可以用orgainztion代替Collaborators?

**Comment by scribetw** [comment]
@Kennyl 他應該是指不是每個人都可以閱覽 [Dashboard](https://app.shippable.com/projects/54c627b95ab6cc135289c573)，事實上我也看不到他的，但他有開權限給我。

https://app.shippable.com/projects/54c7ac995ab6cc135289ec6c/builds/latest
這個是我的，可能也只有我能看到。
或許算規格吧？大家如果有需要 Organization 我可以研究一下開給大家玩。

**Comment by touhonoob** [comment]
後來在Shippable的貼紙發現latest build的連結是公開可見的
只是他的Dashboard要有Collaborator或Organization權限才能看得到

**Comment by Kennyl** [comment]
其實Dashboard 看不倒也不是太重，github 每一次push 都會觸發shippable 的webhook 自動test.
想有dashboard，我想用自己的fork才合適。

**Comment by scribetw** [comment]
感覺 Shippable 算是 Travis-CI 的巨集，它還能自訂 Docker image、彙整測試覆蓋率。
Travis-CI 很明顯要排隊等執行，Shippable 也要不過感覺快一些。Drone.io 幾乎隨 push 隨有，可惜不支援編譯器多版本。

Drone.io 是功能最少的，也不支援 Service hook，但就一個字快。
