### ISSUE TITLE
PHP 最低需求版號上調 >= 5.3.0

### ISSUE THREAD

**Issue by scribetw** [scribetw/pixmicat#22]
\>= 5.3.0 (支援Namespace, Lambda)

我發現 2cat 還在 5.3，因此大概先調到 5.3 即可。

**Comment by scribetw** [comment]
下一次會再將需求上調，不確定是 PHP 5.4 或 5.5。

**Comment by touhonoob** [comment]
話說PHP7快出了XD
https://wiki.php.net/rfc/php7_57_roadmap

**Comment by scribetw** [comment]
@touhonoob 不錯啊，按照 PHP: The Right Way 的標準，若 5.7 出了，5.7/5.6/5.5 就是主流版本，就可以一次抬升最低支援版本了。
* the three most recent stable PHP versions
