### ISSUE TITLE
支援 WebM

### ISSUE THREAD

**Issue by scribetw** [scribetw/pixmicat#24]
先研究是否能接受上傳WebM並嵌入作為動畫。

未來再考慮GIF轉WebM。

**Comment by touhonoob** [comment]
目前有找到兩種方法
第一種是把gif動畫的所有影格拆開，再重組成webm
第二種是直接用avconv,ffmpeg直接轉檔
https://hackpad.com/GIF-to-WebM--BvFP8iSA4u9

**Comment by scribetw** [comment]
@touhonoob 感謝整理，應該會使用 FFMPEG 轉檔。目前還要研究上傳 WebM 後，如何判斷該檔案是否為 WebM (Magic Header?) 與抓取寬高資訊

**Comment by touhonoob** [comment]
參考: https://github.com/MediaCrush/MediaCrush/blob/master/mediacrush/processing/detect.py
```shell
avprobe/ffprobe -print_format json -loglevel quiet -show_format -show_streams
```

**Comment by scribetw** [comment]
感謝 @touhonoob 提供 Pull request #36 解決此題。
