### ISSUE TITLE
ImageMagick 對動畫 GIF 產生預覽圖會針對每個畫格產生多檔

### ISSUE THREAD

**Issue by scribetw** [scribetw/pixmicat#32]
convert -thumbnail 200x200 -quality 50 test.gif tests.jpg

會產生 tests-0.jpg, tests-1.jpg...

[Command-line Processing](http://www.imagemagick.org/script/command-line-processing.php) 的 Selecting Frames 提到動畫 GIF 可用 `test.gif[0]` 方式指定畫格。

**Comment by Kennyl** [comment]
或者簡單一些 
convert -thumbnail 200x200 -quality 50 -flatten test.gif tests.jpg

**Comment by scribetw** [comment]
@Kennyl 希望這個對所有格式都通用，因為我不太想判斷gif才用特殊方法。有空來試看看

**Comment by Kennyl** [comment]
測試成功gif webm jpg 如下
準備test.gif (animate)

convert -flatten test.gif test.jpg
convert -flatten test.gif test.png
convert -flatten test.gif test.webm

convert -thumbnail 200x200 -quality 50 -flatten test.gif gif.jpg
convert -thumbnail 200x200 -quality 50 -flatten test.webm webm.jpg
convert -thumbnail 200x200 -quality 50 -flatten test.jpg jpg.jpg
convert -thumbnail 200x200 -quality 50 -flatten test.png png.jpg
![screen shot 2015-02-10 at 5 57 06 pm](https://cloud.githubusercontent.com/assets/1933134/6125169/4ab3e68a-b14e-11e4-80a5-8a25daef5c8b.png)

**Comment by scribetw** [comment]
@Kennyl 感謝測試，稍晚修正成你建議的命令。
