### ISSUE TITLE
支援 https

### ISSUE THREAD

**Issue by ccpz** [scribetw/pixmicat#33]
主要是因為 spdy ，以及有建議所有網頁使用 https 的風氣:
https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure

之前嘗試在 pixmicat 用 https ，大致上是沒問題，不過在 fileIO getAbsoluteUrl():
https://github.com/scribetw/pixmicat/blob/develop/lib/FileIo/AbstractFileIO.php
這裡寫死 http，會產生 http& https 混用的問題。
如果在設定檔加上變數指定 http 或 https 如何？

**Comment by Kennyl** [comment]
可以參考以下

http://stackoverflow.com/questions/6768793/get-the-full-url-in-php

 $ssl = (!empty($s['HTTPS']) && $s['HTTPS'] == 'on') ? true:false;



2015-02-06 9:06 GMT+08:00 Yi-Ta Chiang <notifications@github.com>:

**Comment by Kennyl** [comment]
如果要改，lib_common 和cgi-pl.pl 也有

**Comment by ytch** [comment]
@Kennyl 

感謝補充，lib_common.php 的 fullURL() 也要改。

$_server 的話，因為  index.htm, 1.htm, 2.htm... 會在後端自動產生。這時也會使用 getAbsoluteUrl()。
他會看現在誰產生 (admin 在管理頁重整/user 發文重整)，就會用當時的協定，而不是用瀏覽時的協定。
因此我覺得不太適合，不知道這樣分析是否有漏洞？

**Comment by ccpz** [comment]
感謝補充，lib_common.php 的 fullURL() 也要改。

$_server 的話，因為 index.htm, 1.htm, 2.htm... 會在後端自動產生。這時也會使用 getAbsoluteUrl()。
他會看現在誰產生 (admin 在管理頁重整/user 發文重整)，就會用當時的協定，而不是用瀏覽時的協定。
因此我覺得不太適合，不知道這樣分析是否有漏洞？

**Comment by Kennyl** [comment]
我覺得前台用https會有issue, 因為不知到cache 不cache 到。 而且也沒有什麼個資訊息

**Comment by ccpz** [comment]
browser 端的 cache 基本上是沒影響, http/https 都是一樣看 header:

http://stackoverflow.com/questions/174348/will-web-browsers-cache-content-over-https

**Comment by scribetw** [comment]
我記得可以用 `://` 來讓瀏覽器自己判斷。

此題的確有必要改，寫死 `http://` 的確不對。
