### ISSUE TITLE
專案頁面移到 GitHub.io

### ISSUE THREAD

**Issue by scribetw** [scribetw/pixmicat#39]
關於 Pixmicat網頁 名稱: 無名氏 [15/05/29(五)21:05 ID:aGB3XC0A] No.3470 推 [回應]

要不要考慮由http://pixmicat.openfoundry.org/ 搬去github.io

**Comment by Kennyl** [comment]
直接把sites  push 去gh-pages才慢慢改link吧

**Comment by scribetw** [comment]
對啊，就先Git push過去再看看

**Comment by Kennyl** [comment]
你直接pull 我的gh-pages 吧。

**Comment by scribetw** [comment]
看起來是建立沒有關聯的 gh-pages 分支即可。

在想是不是順便用產生器建立現代頁面，頁框感覺就是2000年的東西 XD

**Comment by Kennyl** [comment]
那麼 寫好readme.md 好讓 產生器建立 首頁

**Comment by Kennyl** [comment]
http://pixmicat.openfoundry.org/ 已經閉鎖?

**Comment by scribetw** [comment]
真的耶。
晚點弄一下 github.io。

**Comment by scribetw** [comment]
http://scribetw.github.io/pixmicat/

好多東西都變了，Google code跟openfoundry都沒了......
當初如果沒有搬過來GitHub我看連程式碼都掰了。

**Comment by Kennyl** [comment]
http://pixmicat.wikidot.com/ 須不須要加回介紹

**Comment by scribetw** [comment]
暫時把 pixmicat.openfoundry.org 的頁面倒回去了。
但該頁面仍是 2005 年的 style，用 2016 的眼光看起來格外刺眼。

或許未來會改成簡單介紹，主要還是用 GitHub 這樣。

2016-01-03 20:53 GMT+08:00 Kennyl notifications@github.com:

**Comment by ghost** [comment]
現在的網址是 `pixmicat.github.io/pixmicat`
應該另外開一個 Repo 叫 `pixmicat.github.io`，然後將目前的 `gh-pages` branch 直接移到那個 repo 的 `master` 上，網址才會是 `pixmicat.github.io`
之後如果有人發 pull request 也會比較好管理。

**Comment by scribetw** [comment]
@BinotaLIU 
感謝，當初建立組織並轉移專案時沒有注意，導致網址出現兩次 pixmicat。
現在已經根據建議修正了。

https://pixmicat.github.io/
