### ISSUE TITLE
停止开发了吗

### ISSUE THREAD

**Issue by yuyuehunter** [scribetw/pixmicat#42]
官方站也打不开啦，好可惜

**Comment by jarryyen** [comment]
只是被墙了而已，可以打开和下载学
https://www.openfoundry.org/of/projects/492/download <https://www.openfoundry.org/of/projects/492/download>

**Comment by scribetw** [comment]
算沒有意願繼續維護了，理由在 #41 裡有描述。

GitHub 上有 [Release](https://github.com/pixmicat/pixmicat/releases) 可以下載比較新的版本
