### ISSUE TITLE
password

### ISSUE THREAD

**Issue by Meido44** [scribetw/pixmicat#43]
what should be put as the default password to log into admin account? Sorry, I can't read Chinese.

**Comment by scribetw** [comment]
There is no default password to avoid vulnerability. You should generate one before using.

The utility can help you to generate one: https://github.com/pixmicat/pixmicat/blob/master/Utilities/genhash.php.
Or use this snippet: https://www.tehplayground.com/xC6I0v9dyykqOLtR.

Once you get a hash string, update the definition of `ADMIN_HASH` in config.php.

**Comment by Meido44** [comment]
I got it working now. Thank you for the fast reply!
